version: '2'
services:
    jdemo-app:
        image: jdemo
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://jdemo-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=jdemo
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jdemo-mongodb:
        extends:
            file: mongodb.yml
            service: jdemo-mongodb
